<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
             DB::table('users')->where('email', 'seller@stylehub.com')->delete();

    $seller = User::create([
        'name' => 'Fashion Store',
        'email' => 'seller@stylehub.com',
        'password' => bcrypt('password123'),
        'user_type' => 'seller',
        'email_verified_at' => now(),
    ]);

 // Create a seller user first
      
        $products = [
            [
                'name' => 'Classic Cotton T-Shirt',
                'description' => 'Comfortable and stylish cotton t-shirt perfect for everyday wear.',
                'images' => 'https://i.ibb.co/zTYLdzm7/fionaa-trendz-men-mint-green-printed-cotton-blend-round-neck-t-shirt-m-product-images-rvrgpdc3ab-0-2.webp',
                'price' => 29.99,
                'original_price' => 39.99,
                'category' => 'men',
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['Black', 'White', 'Navy'],
                'stock_quantity' => 100,
                'seller_id' => $seller->id,
                'status' => 'active',
                'featured' => true,
            ],
            [
                'name' => 'Elegant Summer Dress',
                'description' => 'Beautiful summer dress perfect for any occasion.',
                'images' => 'https://i.postimg.cc/85DXngcb/images.jpg',
                'price' => 79.99,
                'original_price' => 99.99,
                'category' => 'women',
                'sizes' => ['XS', 'S', 'M', 'L'],
                'colors' => ['Floral', 'Solid Blue', 'Red'],
                'stock_quantity' => 50,
                'seller_id' => $seller->id,
                'status' => 'active',
                'featured' => true,
            ],
            [
                'name' => 'Kids Denim Jacket',
                'description' => 'Stylish denim jacket for kids.',
                'images' => 'https://i.ibb.co/djTn9vH/kids-denim-jacket.webp',
                'price' => 49.99,
                'original_price' => 59.99,
                'category' => 'kids',
                'sizes' => ['2T', '3T', '4T', '5T'],
                'colors' => ['Light Blue', 'Dark Blue'],
                'stock_quantity' => 30,
                'seller_id' => $seller->id,
                'status' => 'active',
                'featured' => false,
            ],
            [
                'name' => 'Men\'s Slim Fit Jeans',
                'description' => 'Trendy slim fit jeans for everyday style.',
                'images' => 'https://i.ibb.co/3fNVQDC/mens-jeans.webp',
                'price' => 59.99,
                'original_price' => 69.99,
                'category' => 'men',
                'sizes' => ['30', '32', '34', '36'],
                'colors' => ['Black', 'Indigo'],
                'stock_quantity' => 80,
                'seller_id' => $seller->id,
                'status' => 'active',
                'featured' => true,
            ],
            [
                'name' => 'Women\'s Floral Skirt',
                'description' => 'Casual floral skirt for summer vibes.',
                'images' => 'https://i.ibb.co/GQ9qSYF/women-floral-skirt.webp',
                'price' => 34.99,
                'original_price' => 49.99,
                'category' => 'women',
                'sizes' => ['S', 'M', 'L'],
                'colors' => ['Pink Floral', 'Blue Floral'],
                'stock_quantity' => 40,
                'seller_id' => $seller->id,
                'status' => 'active',
                'featured' => false,
            ],
            [
                'name' => 'Kids Cartoon Hoodie',
                'description' => 'Warm hoodie with cartoon prints for kids.',
                'images' => 'https://i.ibb.co/J2kBB3c/kids-hoodie.webp',
                'price' => 39.99,
                'original_price' => 49.99,
                'category' => 'kids',
                'sizes' => ['4T', '5T', '6T'],
                'colors' => ['Red', 'Yellow'],
                'stock_quantity' => 25,
                'seller_id' => $seller->id,
                'status' => 'active',
                'featured' => true,
            ],
            [
                'name' => 'Men\'s Formal Shirt',
                'description' => 'Perfect for office and formal occasions.',
                'images' => 'https://i.ibb.co/WksVgSr/formal-shirt.webp',
                'price' => 44.99,
                'original_price' => 54.99,
                'category' => 'men',
                'sizes' => ['M', 'L', 'XL'],
                'colors' => ['White', 'Sky Blue'],
                'stock_quantity' => 60,
                'seller_id' => $seller->id,
                'status' => 'active',
                'featured' => false,
            ],
            [
                'name' => 'Women\'s Workout Leggings',
                'description' => 'Stretchable and comfortable workout leggings.',
                'images' => 'https://i.ibb.co/LCPGM35/leggings.webp',
                'price' => 24.99,
                'original_price' => 34.99,
                'category' => 'women',
                'sizes' => ['S', 'M', 'L'],
                'colors' => ['Black', 'Gray'],
                'stock_quantity' => 75,
                'seller_id' => $seller->id,
                'status' => 'active',
                'featured' => true,
            ],
            [
                'name' => 'Kids Cotton Pajamas',
                'description' => 'Soft cotton sleepwear set for kids.',
                'images' => 'https://i.ibb.co/4V7sTS8/kids-pajamas.webp',
                'price' => 19.99,
                'original_price' => 29.99,
                'category' => 'kids',
                'sizes' => ['3T', '4T', '5T'],
                'colors' => ['White Stars', 'Blue Dots'],
                'stock_quantity' => 35,
                'seller_id' => $seller->id,
                'status' => 'active',
                'featured' => false,
            ],
            [
                'name' => 'Men\'s Sports Jacket',
                'description' => 'Windproof and lightweight sports jacket.',
                'images' => 'https://i.ibb.co/zr0Tmpp/sports-jacket.webp',
                'price' => 69.99,
                'original_price' => 89.99,
                'category' => 'men',
                'sizes' => ['M', 'L', 'XL'],
                'colors' => ['Navy', 'Olive Green'],
                'stock_quantity' => 55,
                'seller_id' => $seller->id,
                'status' => 'active',
                'featured' => true,
            ],
            [
                'name' => 'Women\'s Cardigan Sweater',
                'description' => 'Cozy knitted cardigan for chilly evenings.',
                'images' => 'https://i.ibb.co/h8LPbG0/cardigan.webp',
                'price' => 59.99,
                'original_price' => 74.99,
                'category' => 'women',
                'sizes' => ['S', 'M', 'L'],
                'colors' => ['Cream', 'Lavender'],
                'stock_quantity' => 45,
                'seller_id' => $seller->id,
                'status' => 'active',
                'featured' => false,
            ],
            [
                'name' => 'Kids Raincoat',
                'description' => 'Colorful waterproof raincoat for kids.',
                'images' => 'https://i.ibb.co/4pSLXBh/raincoat.webp',
                'price' => 27.99,
                'original_price' => 39.99,
                'category' => 'kids',
                'sizes' => ['3T', '4T', '5T'],
                'colors' => ['Yellow', 'Blue'],
                'stock_quantity' => 20,
                'seller_id' => $seller->id,
                'status' => 'active',
                'featured' => true,
            ],
            [
                'name' => 'Men\'s Hoodie',
                'description' => 'Casual hoodie with front pocket.',
                'images' => 'https://i.ibb.co/tzDjM6W/mens-hoodie.webp',
                'price' => 49.99,
                'original_price' => 59.99,
                'category' => 'men',
                'sizes' => ['M', 'L', 'XL'],
                'colors' => ['Black', 'Gray'],
                'stock_quantity' => 90,
                'seller_id' => $seller->id,
                'status' => 'active',
                'featured' => false,
            ],
            [
                'name' => 'Women\'s Party Gown',
                'description' => 'Elegant long gown for evening parties.',
                'images' => 'https://i.ibb.co/q7rcDtY/party-gown.webp',
                'price' => 119.99,
                'original_price' => 149.99,
                'category' => 'women',
                'sizes' => ['S', 'M', 'L'],
                'colors' => ['Red', 'Emerald Green'],
                'stock_quantity' => 20,
                'seller_id' => $seller->id,
                'status' => 'active',
                'featured' => true,
            ],
            [
                'name' => 'Kids T-Shirt Pack (3 pcs)',
                'description' => 'Colorful t-shirt combo for kids.',
                'images' => 'https://i.ibb.co/yV7fBgD/kids-tshirts.webp',
                'price' => 24.99,
                'original_price' => 34.99,
                'category' => 'kids',
                'sizes' => ['2T', '3T', '4T'],
                'colors' => ['Mixed'],
                'stock_quantity' => 50,
                'seller_id' => $seller->id,
                'status' => 'active',
                'featured' => false,
            ],
            [
                'name' => 'Men\'s Cotton Shorts',
                'description' => 'Breathable cotton shorts for summer.',
                'images' => 'https://i.ibb.co/jJzVDTF/mens-shorts.webp',
                'price' => 22.99,
                'original_price' => 29.99,
                'category' => 'men',
                'sizes' => ['M', 'L', 'XL'],
                'colors' => ['Khaki', 'Blue'],
                'stock_quantity' => 70,
                'seller_id' => $seller->id,
                'status' => 'active',
                'featured' => false,
            ],
            [
                'name' => 'Women\'s Scarf Set',
                'description' => 'Soft and elegant scarf in pack of 2.',
                'images' => 'https://i.ibb.co/zJwrLBS/scarf.webp',
                'price' => 19.99,
                'original_price' => 29.99,
                'category' => 'women',
                'sizes' => ['Free'],
                'colors' => ['Beige', 'Maroon'],
                'stock_quantity' => 65,
                'seller_id' => $seller->id,
                'status' => 'active',
                'featured' => false,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
